name: BiTro
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0=cuda
  - pyg=2.6.1=py310_torch_2.3.0_cu118
  - mpi4py=3.1.3
  - numpy-base=2.0.1
  - networkx=3.4.2
  - pillow=11.1.0
  - pyyaml=6.0.2
  - requests=2.32.3
  - pip:
      - torch==2.6.0+cu124
      - torchvision==0.21.0+cu124
      - torchaudio==2.6.0+cu124
      - torch-geometric
      - torch-scatter==2.1.2+pt25cu121
      - torch-sparse==0.6.18+pt25cu121
      - torch-cluster==1.6.3+pt25cu121
      - torch-spline-conv==1.2.2+pt25cu121
      - pyg-lib==0.4.0+pt25cu121
      - torch-kmeans==0.2.0
      - anndata==0.11.4
      - scanpy==1.11.3
      - pandas==2.2.3
      - numpy==2.2.4
      - scipy==1.15.2
      - scikit-learn==1.6.1
      - scikit-image==0.25.2
      - matplotlib==3.10.1
      - seaborn==0.13.2
      - tqdm==4.67.1
      - h5py==3.14.0
      - imageio==2.37.0
      - opencv-python==4.11.0.86
      - openslide-python==1.4.2
      - tifffile==2025.5.10
      - timm==1.0.16
      - transformers==4.50.3
      - huggingface-hub==0.29.3
      - safetensors==0.5.3
      - einops==0.8.1
      - loralib==0.1.2
      - deepspeed==0.16.7
      - datasets==4.0.0
      - umap-learn==0.5.7
      - hdbscan==0.8.40
      - pynndescent==0.5.13
      - numba==0.61.2
      - joblib==1.4.2
      - statsmodels==0.14.4
      - shapely==2.1.1
      - staintools==2.1.2
      - spams-bin==2.6.13
      - openpyxl==3.1.5
      - pyarrow==19.0.1
      - fsspec==2025.3.0
      - filelock==3.18.0
      - packaging==24.2
      - pydantic==2.11.3
      - bokeh==3.7.2
      - ninja==1.11.1.4
      - regex==2024.11.6
      - tokenizers==0.21.1
      - sympy==1.13.1
      - triton==3.2.0
